#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo "You have uncommitted changes in your workspace. Please commit or stash them before pushing to ensure e2e tests reflect code to be pushed. I know. It's not ideal, but its better than the 2 alternatives: git worktree and docker."
    exit 1
fi

# 1) Run build:test
cd frontend && npm run build:test

# 2) Serve the result at localhost:3000 in the background
npm run start:test &

# Capture the PID of the server process
SERVER_PID=$!

# Set up a trap to ensure the server is shut down when the script exits
trap 'kill $SERVER_PID' EXIT

# Give the server some time to start
sleep 3

# 3) Run the tests, exit with code 1 if they fail
npx jest --all --env node --testMatch "**/?(*.)+(e2e.test).[jt]s?(x)" || exit 1

# 4) Exit the Husky script with code 0
exit 0
