service: btcfix
useDotenv: true

provider:
  name: aws
  stage: dev
  runtime: nodejs18.x
  region: us-east-2

plugins:
  - serverless-lift
  - serverless-scriptable-plugin

custom:
  scriptable:
    hooks:
      package:initialize: "sh ./ci/build.sh"

constructs:
  website:
    type: single-page-app
    path: build
    domain:
      - doesbitcoinhelp.com
      - www.doesbitcoinhelp.com
    certificate: arn:aws:acm:us-east-1:974540871118:certificate/671ba455-b9c0-49a4-b5c6-c735eedb4833

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${env:HOSTED_ZONE_ID}
        Name: doesbitcoinhelp.com
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:website.cname}
    Route53RecordWWW:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: ${env:HOSTED_ZONE_ID}
        Name: www.doesbitcoinhelp.com
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:website.cname}
