name: Deploy

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Deploy
        env:
          STAGE: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

          # Backend
          GPT_VERSION_dev: ${{ secrets.GPT_VERSION_DEV }}
          GPT_VERSION_prod: ${{ secrets.GPT_VERSION_PROD }}
          DATABASE_URL_dev: ${{ secrets.DATABASE_URL_DEV }}
          DATABASE_URL_prod: ${{ secrets.DATABASE_URL_PROD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_VPC_SECURITY_GROUP: ${{ secrets.AWS_VPC_SECURITY_GROUP }}
          AWS_VPC_SUBNET_1: ${{ secrets.AWS_VPC_SUBNET_1 }}
          AWS_VPC_SUBNET_2: ${{ secrets.AWS_VPC_SUBNET_2 }}
          AWS_VPC_SUBNET_3: ${{ secrets.AWS_VPC_SUBNET_3 }}
          AWS_IOT_CLIENT_ID: ${{ secrets.AWS_IOT_CLIENT_ID }}
          AWS_IOT_HOST: ${{ secrets.AWS_IOT_HOST }}

          # Frontend
          DISABLE_ESLINT_PLUGIN: true
          REACT_APP_API_URL_HTTP_DEV: ${{ secrets.REACT_APP_API_URL_HTTP_DEV }}
          REACT_APP_API_URL_HTTP_PROD: ${{ secrets.REACT_APP_API_URL_HTTP_PROD }}
          REACT_APP_API_URL_WS_DEV: ${{ secrets.REACT_APP_API_URL_WS_DEV }}
          REACT_APP_API_URL_WS_PROD: ${{ secrets.REACT_APP_API_URL_WS_PROD }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CERTIFICATE_ID: ${{ secrets.CERTIFICATE_ID }}

        run: ./deploy.sh $STAGE
